import Head from 'next/head'
import useTranslation from 'next-translate/useTranslation'
import Layout from '@/components/layout/layout'
import { Corousel } from '@/components/corousel'
import { NextPage, NextPageContext } from 'next'
import setLanguage from 'next-translate/setLanguage'
import { useEffect } from 'react'
interface Props {
  userAgent?: string;
  language?:string;
}
const Home:NextPage<Props>=({userAgent,language}) => {
  const { t, lang } = useTranslation('common')
  const example = t('variable-example', { count: 42 })
  useEffect(()=>{
    if(setLanguage != undefined){
      // setLanguage(language as string)
    }
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
      
      <h1>{example}</h1>
      
      <div className=''>{userAgent}</div>
      <div className=''>{language}</div>
      <Corousel/>
      <div className=''>{userAgent}</div>
      <div className=''>{language}</div>
      <Corousel/>
      <div className=''>{userAgent}</div>
      <div className=''>{language}</div>
      <Corousel/>
    </Layout>
    </>
  )
}
Home.getInitialProps = async ({ req,res,pathname,query }) => {
  // res?.setHeader('set-cookie', ['access-token=1', 'refresh-token=1'])
  const userAgent = req ? req.headers['user-agent'] : navigator.userAgent
  const lang =req ? req.headers["accept-language"]: navigator.language; 
  const lastIndex = lang?.lastIndexOf(',') || 4
  const language =  lang?.substring(1+lastIndex)
  return { userAgent,language }

}

export default Home;